language: java
jdk:
  - openjdk8

# SKipping entirely the automatin install phare done by travis
install: skip

addons:
  sonarcloud:
    organization: "ultrale"
    token: 601e60278def586e544dfb3ff19b6087c9c69e8d

script:
  #the actual used offline:
  #-mvn clean verify -pl bookkeeper-server -Dtest=PitTest
  - mvn clean -pl bookkeeper-server -Dtests=PitTest org.jacoco:jacoco-maven-plugin:prepare-agent verify org.pitest:pitest-maven:mutationCoverage sonar:sonar -Dsonar.projectKey=UltraLe_JacocoBaduaPit