language: java
jdk:
  - openjdk8

# SKipping entirely the automatin install phare done by travis
install: true

# Skip automatic git pull of all submodules
git:
  submodules: false

addons:
  sonarcloud:
    organization: "ultrale"
    token: 601e60278def586e544dfb3ff19b6087c9c69e8d

script:
  # TODO try with ,. and -e flag to see full stack trace
  - mvn clean verify -Dtest=PitTest org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=UltraLe_bookkeeper