language: java
jdk:
  - openjdk8

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean
  #the actual used offline:
  #-mvn clean verify -pl testscustom -pl bookkeeper-server -Dtest=PitTest
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.pitest:pitest-maven:mutationCoverage sonar:sonar -Dsonar.projectKey=UltraLe_JacocoBaduaPit
  #- mvn clean verify sonar:sonar -Dsonar.projectKey=UltraLe_JacocoBaduaPit