language: java
jdk:
  - openjdk8

# SKipping entirely the automatic install phase done by travis
install: true

# Skip automatic git pull of all submodules
git:
  submodules: false

addons:
  sonarcloud:
    organization: "ultrale"
    token: 601e60278def586e544dfb3ff19b6087c9c69e8d

script:
  - mvn clean
  #- mvn clean -pl .,bookkeeper-server -Dtest=PitTest org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=UltraLe_bookkeeper -DfailIfNoTests=false -X